source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set nu
set ruler  "show the cursor position all the time
set fileencodings=utf-8,gbk,ucs-bom,cp936 
"set encoding=utf-8
"set ignorecase
"set noignorecase

set ts=4
set sw=4
set autoindent
set smartindent
set cin
set expandtab

set nocompatible
set nowrap " do not fold line 
set tags=tags
"set autochdir
syntax on

"color evening
"colorscheme desert

syntax enable
set background=dark
colorscheme solarized

"syntax enable
"set background=light
"colorscheme solarized

" << configure the status bar
"set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2    
" configure the status bar >> 

call pathogen#infect()


" auto completaiton
filetype plugin indent on
set completeopt=longest,menu

"let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
nmap T <ESC>:TlistToggle<CR>

let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm :WMToggle<cr>

" << configure c.vim
let g:C_SourceCodeExtensions  = 'h c cp cxx cpp CPP c++ C i ii'
" configure c.vim >>
"
" << configure cscope  
nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>t :cs find t <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>e :cs find e <C-R>=expand("<cword>")<CR><CR>
nmap <C-\>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
nmap <C-\>i :cs find i <C-R>=expand("<cfile>")<CR><CR>
nmap <C-\>d :cs find d <C-R>=expand("<cword>")<CR><CR>
"set cscopequickfix=s-,c-,d-,i-,t-,e-
nmap <C-n> :cn<cr>
nmap <C-p> :cp<cr>
"nmap <F5> :cn<cr>
"nmap <F6> :cp<cr>
